#!/usr/bin/env python
# calculate_eda_snakes Calcula resumen de 5 numeros de datos serpientes Isla Isabel.
import numpy as np
import pandas as pd

s = pd.read_csv("data/raw/monitoreo_serpiente_falsa_coralillo_isla_isabel_2008-2014.csv")
s = s.rename(
    columns={
        "Longitud_total": "Total",
        "Longitud_hocico_cola": "Hocico-Cola",
        "Longitud_cloaca_cola": "Cloaca-Cola",
        "Masa_del_individuo": "Masa (g)",
        "Elevacion": "Elevacion",
    }
)
s = s.describe()
s = s.rename(index={"25%": "$Q_1$", "50%": "$Q_2$", "75%": "$Q_3$"})
s = s.rename_axis("Estadistico")
s.drop(columns=["Temporada", "Latitud", "Longitud"]).round(decimals=2).to_csv(
    "reports/tables/resumen_cinco_numero_serpientes.csv"
)
