#!/usr/bin/env python
# calculate_eda_snakes Calcula resumen de 5 numeros de datos serpientes Isla Isabel.
import numpy as np
import pandas as pd

summary_five_numbers = pd.read_csv("data/raw/monitoreo_serpiente_falsa_coralillo_isla_isabel_2008-2014.csv")
summary_five_numbers = summary_five_numbers.rename(
    columns={
        "Longitud_total": "Total",
        "Longitud_hocico_cola": "Hocico-Cola",
        "Longitud_cloaca_cola": "Cloaca-Cola",
        "Masa_del_individuo": "Masa (g)",
        "Elevacion": "Elevacion",
    }
)
summary_five_numbers = summary_five_numbers.describe().T
summary_five_numbers = summary_five_numbers.rename_axis("Variable") 
summary_five_numbers.round(decimals=2).to_csv("reports/tables/resumen_cinco_numero_serpientes.csv")
